[package]
name = "git-swift"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
gemini-rs = "0.4.2"
git2 = "0.20.0"
reqwest = { version = "0.12.12", features = ["json"] }
tokio = { version = "1.43.0", features = ["full"] }
