version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - RUST_LOG=info
      - GROQ_API_KEY=${GROQ_API_KEY}
    env_file:
      - .env
    restart: unless-stopped

networks:
  default:
    driver: bridge
